# Generated by Django 3.2.3 on 2021-05-17 14:17

from django.db import migrations
import slugs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('slugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='order',
            field=slugs.fields.OrderField(blank=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=slugs.fields.OrderField(blank=True),
        ),
    ]
