# Generated by Django 3.2.3 on 2021-05-14 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slugs', '0002_auto_20210514_0333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='group',
            new_name='messages',
        ),
    ]
